module.exports = {
    USER_COLLECTION: 'user',
    ADMIN_COLLECTION: 'admin',
    COURSES_COLLECTION: 'courses',
    DEPARTMENTS_COLLECTION: 'departments',
    BATCHES_COLLECTION: 'batches',
    FAMILY_MEMBERS_COLLECTION: 'family_members',
    REGISTRATION_COLLECTION: 'registration',
    GENDER_COLLECTION: 'gender',
    APPLICATION_COLLECTION: 'applications',
    SCHOLARSHIP_COLLECTION: 'scholarships',
    ACADEMIC_YEAR_COLLECTION: 'academic_year',
    APPLICAION_STATUS: 'application_status',
    SCHOLARSHIP_LIST_COLLECTION:'scholarship_list',
    DISTRICT_COLLECTION:'districts',
    STATE_COLLECTION:'states',
    TALUK_COLLECTION:'taluks',
    LOCALBODY_COLLECTION:'localbodys',
    APPLICATION_PERSONAL_DETAILS_COLLECTION:'application_personal_details',
    APPLICATION_CONTACT_DETAILS_COLLECTION:'application_contact_details',
    APPLICATION_ACADEMIC_DETAILS_COLLECTION:'application_academic_details',
    BANK_DETAILS_COLLECTION:'bank_details',
    PASSWORD_FORGOT_COLEECTION:'forgot_password'
}